environment:
  matrix:
    - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64'
      MSYS: 'C:\msys64\mingw64'
      #  QTDIR: 'C:\Qt\5.13\mingw73_64'
      GENERATOR: "MinGW Makefiles"
      BUILD_TYPE: "Debug"
      BITS: 'mingw64/mingw-w64-x86_64'
      
    # - MINGW: 'C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64'
    #   MSYS: 'C:\msys64\mingw64'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Debug"
    #   BITS: 'mingw64/mingw-w64-x86_64'
      
    # - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Release"
    #   BITS: 'mingw64/mingw-w64-x86_64'

image:
  - "Visual Studio 2015"

before_build:
  cmd: |-
      set PATH=C:\Python38;%PATH%
      python -m pip install pefile
      python -c "import pefile"
      rem set PATH=%MINGW%\bin;%PATH%
      echo %APPVEYOR_API_URL%

      c:\msys64\usr\bin\pacman -Ss libarchive
      c:\msys64\usr\bin\pacman -Ss libsndfile
      c:\msys64\usr\bin\pacman -Ss cppunit
      c:\msys64\usr\bin\pacman -Ss portaudio
      c:\msys64\usr\bin\pacman -Ss pthreads

      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libarchive
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libsndfile
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-cppunit
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-portaudio
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libwinpthread-git
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-qt5

      set QTDIR=%MSYS%
      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=%MSYS%\bin;%QTDIR%\bin;%PATH%
      set PKG_CONFIG_PATH="c:\msys64\mingw64\lib\pkgconfig"

      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
      echo %PATH%
      rem mkdir build
      rem cd build
      cd windows
      cmake --version
      cmake -G "%GENERATOR%" ..

build:
  verbosity: detailed

build_script:
  - cmd: |-
      cmake --build . --config %BUILD_TYPE%

      set H2_HOME=%APPVEYOR_BUILD_FOLDER%
      echo %H2_HOME%
      cd
      SET CORE_PATH=%cd%\src\core
      echo %CORE_PATH%
      set PATH=%CORE_PATH%;%PATH%
      src\tests\tests.exe

      mkdir ..\windows\extralibs
      echo "Hello" > ..\windows\extralibs\hello.txt
      mkdir windows\extralibs
      echo "World" > windows\extralibs\world.txt

      python %APPVEYOR_BUILD_FOLDER%\windows\copy_thirdparty_dlls.py -L %MSYS%\bin -d %APPVEYOR_BUILD_FOLDER%\windows\extralibs -V debug src/gui/hydrogen.exe src/core/libhydrogen-core-1.0.0.dll
      %QTDIR%\bin\windeployqt.exe -xmlpatterns --dir extralibs src/gui/hydrogen.exe

      cmake --build . --target install
      tree "C:\Program Files (x86)\hydrogen" /A /F

      cpack -G NSIS

artifacts:

on_finish:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
