environment:
  QTDIR: "C:\\Qt\\5.11.1\\msvc2017_64"
  CMAKE_PREFIX_PATH: "C:\\Qt\\5.11.1\\msvc2017_64"

image:
  - "Visual Studio 2017"

before_build:
  cmd: |-
      vcpkg integrate install
      vcpkg install libarchive libsndfile portaudio cppunit
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Visual Studio 15 2017 Win64"

build:
  verbosity: detailed
