environment:
  QTDIR: "C:\\Qt\\5.11.1\\msvc2015"
  CMAKE_PREFIX_PATH: "C:\\Qt\\5.11.1\\msvc2015"
  
  #VCPKG_DEFAULT_TRIPLET: "x64-windows"

image:
  - "Visual Studio 2015"

before_build:
  cmd: |-
      vcpkg install libarchive libsndfile portaudio cppunit
      vcpkg integrate install
      mkdir build
      cd build
      cmake --version
      cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 14 2015" ..

build:
  verbosity: detailed
