environment:
  - QTDIR: "C:\Qt\5.11.1"

image:
  - "Visual Studio 2017"

before_build:
  cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Visual Studio 15 2017 Win64"

build:
  verbosity: detailed
