environment:
  matrix:
    - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64'
      MSYS: 'C:\msys64\mingw64'
      #  QTDIR: 'C:\Qt\5.13\mingw73_64'
      GENERATOR: "MinGW Makefiles"
      BUILD_TYPE: "Debug"
      BITS: 'mingw64/mingw-w64-x86_64'
      
    # - MINGW: 'C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64'
    #   MSYS: 'C:\msys64\mingw64'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Debug"
    #   BITS: 'mingw64/mingw-w64-x86_64'
      
    # - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Release"
    #   BITS: 'mingw64/mingw-w64-x86_64'

image:
  - "Visual Studio 2015"

before_build:
  cmd: |-
      rem set PATH=%MINGW%\bin;%PATH%
      echo %APPVEYOR_API_URL%

      c:\msys64\usr\bin\pacman -Ss libarchive
      c:\msys64\usr\bin\pacman -Ss libsndfile
      c:\msys64\usr\bin\pacman -Ss cppunit
      c:\msys64\usr\bin\pacman -Ss portaudio
      c:\msys64\usr\bin\pacman -Ss pthreads

      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libarchive
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libsndfile
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-cppunit
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-portaudio
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libwinpthread-git
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-qt5

      set QTDIR=%MSYS%
      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=%MSYS%\bin;%QTDIR%\bin;%PATH%
      set PKG_CONFIG_PATH="c:\msys64\mingw64\lib\pkgconfig"

      mkdir dll
      bash -lc "for DLL in c:/msys64/mingw64/bin/*.dll; do objdump -p $DLL > dll/`basename $DLL`.txt; done; tar czf dll.tar.gz dll"

      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
      echo %PATH%
      rem mkdir build
      rem cd build
      cd windows
      cmake --version
      cmake -G "%GENERATOR%" ..

build:
  verbosity: detailed

build_script:
  - cmd: |-
      cmake --build . --config %BUILD_TYPE%

      

      mkdir windows
      copy "src\gui\hydrogen.exe" windows
      copy "src\core\libhydrogen-core-1.0.0.dll" windows
      copy "src\tests\tests.exe" windows

      objdump -p "src\gui\hydrogen.exe" > hydrogen.exe.txt
      objdump -p "src\core\libhydrogen-core-1.0.0.dll" > libhydrogen-core-1.0.0.dll.txt
      objdump -p "src\tests\tests.exe" > tests.exe.txt
      ls %SystemRoot%\system32 > system32.txt
      ls %SystemRoot% > systemroot.txt
      bash -lc "tar czf exe.tar.gz hydrogen.exe.txt libhydrogen-core-1.0.0.dll.txt tests.exe.txt system32.txt systemroot.txt"


      set H2_HOME=%APPVEYOR_BUILD_FOLDER%
      echo %H2_HOME%
      windows\tests.exe

      mkdir ..\windows\extralibs
      echo "Hello" > ..\windows\extralibs\hello.txt
      mkdir windows\extralibs
      echo "World" > windows\extralibs\world.txt

      %QTDIR%\bin\windeployqt.exe -xmlpatterns --dir extralibs src/gui/hydrogen.exe

      cmake --build . --target install
      tree "C:\Program Files (x86)\hydrogen" /A /F

      cpack -G NSIS

      copy "%MSYS%\bin\libFLAC-8.dll" windows
      copy "%MSYS%\bin\libarchive-13.dll" windows
      copy "%MSYS%\bin\libbz2-1.dll" windows
      copy "%MSYS%\bin\libexpat-1.dll" windows
      copy "%MSYS%\bin\liblz4.dll" windows
      copy "%MSYS%\bin\liblzma-5.dll" windows
      copy "%MSYS%\bin\libnettle-7.dll" windows
      copy "%MSYS%\bin\libogg-0.dll" windows
      copy "%MSYS%\bin\libportaudio-2.dll" windows
      copy "%MSYS%\bin\libsndfile-1.dll" windows
      copy "%MSYS%\bin\libspeex-1.dll" windows
      copy "%MSYS%\bin\libwinpthread-1.dll" windows
      copy "%MSYS%\bin\libzstd.dll" windows
      copy "%MSYS%\bin\libvorbis-0.dll" windows
      copy "%MSYS%\bin\libvorbisenc-2.dll" windows
      copy "%MSYS%\bin\libcppunit-1-14-0.dll" windows
      copy "%MSYS%\bin\libgcc_s_seh-1.dll" windows
      copy "%MSYS%\bin\libstdc++-6.dll" windows

      file windows/*

      bash -lc "tar czvf files.tar.gz c:/msys64/mingw64/bin src/core/libhydrogen-core-1.0.0.dll src/gui/hydrogen.exe"

      cpack -G NSIS

artifacts:
  - path: dll.tar.gz
    name: objdump DLL
  - path: windows/exe.tar.gz
    name: objdump EXE
  - path: windows/files.tar.gz
    name: Built DLLs

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
