environment:
  matrix:
    - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64'
      MSYS: 'C:\msys64\mingw64'
      #  QTDIR: 'C:\Qt\5.13\mingw73_64'
      GENERATOR: "MinGW Makefiles"
      BUILD_TYPE: "Debug"
      BITS: 'mingw64/mingw-w64-x86_64'
      
    # - MINGW: 'C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64'
    #   MSYS: 'C:\msys64\mingw64'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Debug"
    #   BITS: 'mingw64/mingw-w64-x86_64'
      
    # - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Release"
    #   BITS: 'mingw64/mingw-w64-x86_64'

image:
  - "Visual Studio 2015"

before_build:
  cmd: |-
      set PATH=%MINGW%\bin;%PATH%
      echo %APPVEYOR_API_URL%
      curl -v -X POST -d "{"^""testName"^"": "^""First test"^"", "^""testFramework"^"": "^""CppUnit"^"", "^""fileName"^"": "^""first.cpp"^"", "^""outcome"^"": "^""Passed"^""}" "%APPVEYOR_API_URL%"api/tests
      curl -v -X POST -d "{"^""testName"^"": "^""Second test"^"", "^""testFramework"^"": "^""CppUnit"^"", "^""fileName"^"": "^""second.cpp"^"", "^""outcome"^"": "^""Passed"^""}" "%APPVEYOR_API_URL%"api/tests

      c:\msys64\usr\bin\pacman -Ss libarchive
      c:\msys64\usr\bin\pacman -Ss libsndfile
      c:\msys64\usr\bin\pacman -Ss cppunit
      c:\msys64\usr\bin\pacman -Ss portaudio
      c:\msys64\usr\bin\pacman -Ss pthreads

      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libarchive
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libsndfile
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-cppunit
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-portaudio
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libwinpthread-git
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-qt5

      set QTDIR=%MSYS%
      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=%MSYS%\bin;%QTDIR%\bin;%PATH%
      set PKG_CONFIG_PATH="c:\msys64\mingw64\lib\pkgconfig"

      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
      echo %PATH%
      mkdir build
      cd build
      cmake --version
      cmake -G "%GENERATOR%" ..

build:
  verbosity: detailed

build_script:
  - cmd: |-
      cmake --build . --config %BUILD_TYPE%

      

      mkdir windows
      copy "src\gui\hydrogen.exe" windows
      copy "src\core\libhydrogen-core-1.0.0.dll" windows
      copy "src\tests\tests.exe" windows

      set H2_HOME=%APPVEYOR_BUILD_FOLDER%
      echo %H2_HOME%
      windows\tests.exe

      copy "%MSYS%\bin\libFLAC-8.dll" windows
      copy "%MSYS%\bin\libarchive-13.dll" windows
      copy "%MSYS%\bin\libbz2-1.dll" windows
      copy "%MSYS%\bin\libexpat-1.dll" windows
      copy "%MSYS%\bin\liblz4.dll" windows
      copy "%MSYS%\bin\liblzma-5.dll" windows
      copy "%MSYS%\bin\libnettle-7.dll" windows
      copy "%MSYS%\bin\libogg-0.dll" windows
      copy "%MSYS%\bin\libportaudio-2.dll" windows
      copy "%MSYS%\bin\libsndfile-1.dll" windows
      copy "%MSYS%\bin\libspeex-1.dll" windows
      copy "%MSYS%\bin\libwinpthread-1.dll" windows
      copy "%MSYS%\bin\libzstd.dll" windows
      copy "%MSYS%\bin\libvorbis-0.dll" windows
      copy "%MSYS%\bin\libvorbisenc-2.dll" windows
      copy "%MSYS%\bin\libcppunit-1-14-0.dll" windows
      copy "%MSYS%\bin\libgcc_s_seh-1.dll" windows
      copy "%MSYS%\bin\libstdc++-6.dll" windows

      file windows/*

      %QTDIR%\bin\windeployqt.exe -xmlpatterns windows\hydrogen.exe


      cpack -G NSIS

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
