environment:
  #VCPKG_DEFAULT_TRIPLET: "x64-windows"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
     - ENV_NAME: MinGW 32
       COMPILER: MinGW
       VCPKG_DEFAULT_TRIPLET: "x86-windows"
       QTDIR: "C:\\Qt\\5.11.1\\mingw53_32"
       GENERATOR: "MinGW Makefiles"
       SDK: "C:\\mingw-w64\\i686-5.3.0-posix-dwarf-rt_v4-rev0\\mingw32\\bin"

#    - ENV_NAME: MSVC 32
#      COMPILER: MSVC
#      VCPKG_DEFAULT_TRIPLET: "x86-windows"
#      QTDIR: "C:\\Qt\\5.11.1\\msvc2015"
#      GENERATOR: "Visual Studio 14 2015"
#      SDK: ""

#    - ENV_NAME: MSVC 64
#      COMPILER: MSVC
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#      PLATFORM: x64
#      VCPKG_DEFAULT_TRIPLET: "x64-windows"
#      QTDIR: "C:\\Qt\\5.11.1\\msvc2017_64"
#      GENERATOR: "Visual Studio 15 2017 Win64"
#      SDK: ""

image:
  - "Visual Studio 2015"

before_build:
  cmd: |-
      echo %PATH%
      tree c:\msys64 /a /f
      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=%SDK%;%PATH%
      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

      rem vcpkg install libarchive libsndfile portaudio pthreads cppunit
      rem vcpkg integrate install
      rem tree C:\tools\vcpkg\installed /a /f
      mkdir build
      cd build
      cmake --version
      if [%COMPILER%]==[MSVC]  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "%GENERATOR%" ..
      if [%COMPILER%]==[MinGW] cmake -G "%GENERATOR%" ..
      dir
      appveyor PushArtifact CMakeCache.txt

build:
  verbosity: detailed

build_script:
  - cmd: |-
      if [%COMPILER%]==[MSVC]  cmake --build . --target ALL_BUILD -- /maxcpucount:4
      if [%COMPILER%]==[MinGW] cmake --build . 


cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml

artifacts:
  - path: build
    name: CMakeCache.txt
