environment:
  matrix:
    - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0'
      QTDIR: 'C:\Qt\5.13.2\mingw73_64'
      GENERATOR: "MinGW Makefiles"
      BUILD_TYPE: "Debug"
      BITS: 'mingw64/mingw-w64-x86_64'
    # - MINGW: 'C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0'
    #   QTDIR: 'C:\Qt\5.13.2\mingw73_64'
    #   GENERATOR: "MinGW Makefiles"
    #   BUILD_TYPE: "Release"
    #   BITS: 'mingw64/mingw-w64-x86_64'

image:
  - "Visual Studio 2019"

before_build:
  cmd: |-
      c:\msys64\usr\bin\pacman -Ss libarchive
      c:\msys64\usr\bin\pacman -Ss libsndfile
      c:\msys64\usr\bin\pacman -Ss cppunit
      c:\msys64\usr\bin\pacman -Ss portaudio
      c:\msys64\usr\bin\pacman -Ss pthreads

      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libarchive
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libsndfile
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-cppunit
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-portaudio
      c:\msys64\usr\bin\pacman --noconfirm -S %BITS%-libwinpthread-git

      set CMAKE_PREFIX_PATH=%QTDIR%
      set PATH=c:\msys64\mingw64\bin;%MINGW%\bin;%QTDIR%\bin;%PATH%
      set PKG_CONFIG_PATH="c:\msys64\mingw64\lib\pkgconfig"

      rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
      echo %PATH%
      mkdir build
      cd build
      cmake --version
      cmake -G "%GENERATOR%" ..

build:
  verbosity: detailed

build_script:
  - cmd: |-
     cmake --build . --config %BUILD_TYPE%
     cpack -G NSIS

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
