language: cpp

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    # - os: linux
    #   dist: trusty
    #   sudo: required
    - os: osx

addons:
  apt:
    packages:
      - qt5-default
      - libqt5xmlpatterns5-dev
      - libarchive-dev
      - libsndfile1-dev
      - libasound2-dev
      - libjack-jackd2-dev
      - liblo-dev
      - libpulse-dev
      - libportmidi-dev
      - portaudio19-dev
      - libcppunit-dev
      - liblrdf-dev
      - liblash-compat-dev
      - librubberband-dev

before_install:
  - export MACOSX_DEPLOYMENT_TARGET="10.10"
  - xcodebuild -showsdks
  - sudo ln -s /usr/local /opt/local
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ladspa-sdk -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install qt5;
      export CMAKE_PREFIX_PATH="$(brew --prefix qt5)";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install libarchive;
      export PKG_CONFIG_PATH="$(brew --prefix libarchive)/lib/pkgconfig";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsndfile jack pulseaudio cppunit; fi

script:
  - mkdir build && cd build && cmake -DWANT_LASH=1 -DWANT_LRDF=1 -DWANT_RUBBERBAND=1 .. && make VERBOSE=1
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="$(brew --prefix qt5)/bin:$PATH" ../macos/build_dmg.sh -v src/gui/hydrogen.app Hydrogen.dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -l src/gui/hydrogen.app/Contents/MacOS/hydrogen | grep -B 1 -A 3 LC_VERSION_MIN_MACOSX ; fi


deploy:
  provider: releases
  api_key:
    secure: oouFvYsKfgIUS9t9yR+XHJ39VYtRKRvA+ZQcQH59nQu4gKo9TgJFSQQidyutPCZAikcp4pzEjdE0AnVmDxE91RpbQGU5cBCHSR0iRhoU3aovlMrWUAhUmZpWTYGLT+DD5pxa5jLb5lOmPKinlhB8mGq4IVKueS6+4i6cv42jgZWbaurbxOG2HEFXb1IwyD0gZhoEo4MeKltm87CetEZpwsxynl67eVjFbzK+y54foS0ntdG8EmKOp4pVIvFpLNSY7+Ukwdrx9uZfGmQKPN+44wzRNREeTW+iiAoBLYvx9f9vcb6s69ypKURLs+aITF2u51qXqUI334HoRJGQASR0VU0hYTC0r8sjbgH6Bn2RBi9CzygLBzyT0fosQs3HfZLKLokIPKXVWBNqcjiT6lmJn3y3A6PAOWqUwnqELfWddMz7EcehQ+YFNl4WcVcdgsx5zRm2MtMH0uBukWbiY63JFOrBBLGkJDUkf2VwJOWuRmQhMop9Xuy1L61EeeCOOz64Z0EpnDXkEMUq8pZdZ8LMBeTCoi2NmUynWNq6AlieowWr84FJbjeGrGFkQVNY9OUZ8MH4Kzq4sYAaJyDqrwxKdAh3XJB2+okQQAUVRQbt4f2UbdXC2fFoIlRL7vftlfxqx/nyshteSuzSrzhbYw1qwaUNMlBgXXVgR8VzyFkFVIE=
  file: Hydrogen.dmg
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME == "osx"
    all_branches: true
    tags: true
