language: cpp
env:
  global:
  - MAKEFLAGS="-j 2"
jobs:
  include:
  - os: linux
    dist: xenial
  - os: osx
    env:
    - MACOSX_DEPLOYMENT_TARGET="10.12"
  - os: osx
    env:
    - MACOSX_DEPLOYMENT_TARGET="10.10"
    - HOMEBREW_NO_AUTO_UPDATE=1
    - PKG_SUFFIX="-legacy"
    osx_image: xcode9
addons:
  apt:
    packages:
    - qt5-default
    - qttools5-dev
    - qttools5-dev-tools
    - libqt5xmlpatterns5-dev
    - libarchive-dev
    - libsndfile1-dev
    - libasound2-dev
    - libjack-jackd2-dev
    - liblo-dev
    - libpulse-dev
    - libportmidi-dev
    - portaudio19-dev
    - libcppunit-dev
    - liblrdf-dev
    - liblash-compat-dev
    - librubberband-dev
  artifacts:
    paths:
    - build/CMakeFiles/CMakeOutput.log
    - "/tmp/hydrogen"
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ladspa-sdk -y;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s /usr/local /opt/local; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$HOMEBREW_NO_AUTO_UPDATE" -ne "1" ]];
  then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; export CMAKE_PREFIX_PATH="$(brew
  --prefix qt5)"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libarchive; export PKG_CONFIG_PATH="$(brew
  --prefix libarchive)/lib/pkgconfig"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libsndfile jack pulseaudio
  cppunit; fi
script:
- mkdir build && cd build && cmake -DWANT_LASH=1 -DWANT_LRDF=1 -DWANT_RUBBERBAND=1
  .. && make
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH="$(brew --prefix qt5)/bin:$PATH"
  ../macos/build_dmg.sh -v src/gui/hydrogen.app Hydrogen${PKG_SUFFIX}.dmg; fi
- TMPDIR=/tmp src/tests/tests
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cAulzV4BaihDQZnzdsZis8AlE01ZTvux5AlzEuabIO6VwdtTvXY09GaLO+PHGqRSm/N+eNHjAPRDwpC/zpNhWNL1EEu35L0wccleqSEPfXY0UjKbI/obcaZEiWbhWlpwbxOcQdH2vRsJy2fQ5dvbI/VkWeJFnW1mt4ik0fm5mKJtYxznFRBVC7WU+L3ohYsm0voHVnV0BP9W1xPFdLRt4NaunMNaqKn8MNigFO2TA6i5NpWpvtErMviSedupGSl7/V8kXiwbe91xLMAlYY3fkrLecUurNpZjOB/Wcku3P/Ou7B+w4RzBmalAGsZWt0spheeZHYZWypVGXha01u6Zi5c1r/0wcGuO+esCAPsCoG0qXqeZ1/64sk5PHBH2kVMZN08vG3mGEQ7Mg59nHGF8bFnwSHztaeq40hOd7bD0hIViIFRMhPukBm4ypiL+CLOqMsVK9t+X+pJ5NxKnf3Q+WjE5+iXG1mqEiwofT1FH2Ex9AedPMRV73rnnqocZekzZV8ocPY5XtNkqkMSTkx6Z+AyAKVUhbcfpmupBRwOG7ntgT4hqejk850Foo6fPPQyBlXU8ToPzcN+s6bwPUT20wk/0Wq3x1hYctGiP3JfPn5Dbi+Uyr1HuEVB9jKgg7cn3g3/X8+NA/nPufAVo5f1cvd302PR6dISWV3dOryLgh/k=
  file: Hydrogen*.dmg
  file_glob: true
  on:
    repo: elpescado/hydrogen
